language: node_js
node_js:
- 10
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
- export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
install:
- yarn global add codecov
- yarn install
before_script:
- yarn run test
script:
- yarn run build
deploy:
  provider: npm
  email: amirhosseinab@outlook.com
  api_key:
    secure: mPSQJ2wd4pDvpJZ0IBys1b6bmjdJTNHZB0hHy5AwKzwBflbe0rQ4yqaXss+qjKbJLVAgtrAT8NMVmX5Fw+cNgqUsaEWvJxkoZpYtDDC6i7jYT0RJqj+c1w33IOeidMP1pnWVlEzbPMdj7YmNk6ty+dWYTSjmdRdcBWky4xC56I2kqCuSGvNABZMS9L/PEtyvPkyeRE8rbLqmEGF56aCqXLenCy/dBPbgEN9rkeDI2WTEWF6JzwZUUNLj5igSnOOzoeVcl7ERHMSuu3FPRepOMSkWa6Pu+D4L94/kZd80awGjM5LiMqCd+e7qrOgaFSZxwvo9CZAx3n/xXqbOF7+J3BLsPHp+c5XYX+ijkDFQnvInYxo0rM4hXdr1qWSkVwMhkSK4gN+QAkPASlxZ19egIepiFlz4HspFl5RptkHt7ngga3qqYP1yutFLP7gpx4MGcF7TVdF1oUzg8DktelrNo/aOn8oRNKqrF/ApRq9dgvW6oKG+/cxq3udBSErqesfOP5ooPcwueNyCQ8YXUiU8ZRGK99a1CMLDLr96xRVYjP5YgBpDJSdyPjzm1A/nycZrBJGcAJiqtjX3xK46QSViAITWjlOO7JZvc/ybOZjSQ4k/A9qfhTJ382VBsZrTr12NplfwJIaWjSHDuki9Ck0S9QUhHqK/XNvm4lTqCfkWYMU=
  on:
    tags: true
    branch: master
  skip_cleanup: true
